 
 /*CASE STATEMENT - INSTRUCTOR GUIDED*/
 
 /*CREATE A COLUMN THAT GROUPS DATA INTO THE FOLLOWING BUCKETS BASED ON PROOF - CASE STATEMENT
  
    PROOFS >= 100 - WASTED
	BETWEEN 80 and 99 - VERY DRUNK
	BETWEEN 50 and 79 - DRUNK
	LESS THAN 50  - TIPSY*/
	
	
 /*CREATE A COLUMN THAT GROUPS DATA INTO THE FOLLOWING BUCKETS BASED ON SHELF_PRICE	- CASE STATEMENT

	SHELF_PRICE
	SHELF_PRICE < 10.00 - CHEAP
	SHELF_RPICE 10 and 29 - MODERATE
	SHELF_PRICE 30 and 59 - HIGH
	SHELF_PRICE OVER 60 -  EXPENSIVE*/
	

/*USE THE ABOVE CASE STATMENTS TO COUNT THE NUMBER OF PRODUCTS IN THOSE CATEGORIES */



/*CREATE INDEPENDENT COLUMNS FOR THE COUNT OF PRODUCTS FOR EACH BUCKET in PROOFS - COUNT w/ CASE STATMENT  */
	


/* GROUP PRATICE*/

/*INDEPENDENT PRATICE - The PERFECT GIFTS FOR FAMILY

	You are shopping for liquor for your family. They've told you their preferences for liquor below.

	Can you write A SINGLE case statement CALLED 'FAMILY MEMBER' THAT Will ASSIGN the following labels to each product?
	
		MOM
		ITEM DESC - LIKES ORANGE FLAVORED DRINKS
		PROOF - LIKES DRINKS THAT GET HER TIPSY
		CATEGORY NAME - HAD A TERRIBLE EXPERIENCE WITH VODKA in COLLEGE AND WON'T DRINK ANY LONGER. 'FLAVORED VODKA' AND 'IMPORTED VODKA - MISC'
		
		DAD
		ITEM DESC - LIKES COFFEE FLAVORED DRINKS
		PROOF - LIKES DRINKS WITH AN ALCOHOL CONTENT THAT WILL GET HIM MORE THAN TIPSY
		Bottle_size - WANTS TO BE ABLE TO FIT IN HIS COAT POCKET WHEN at work, LESS 750 ML.
		
		BROTHER
		CATEGORY NAME = Became a HUGE FAN OF GIN since binge watching Mad-Men. 'AMERICAN DRY GINS'
		PROOF: LIKES TO GET AT LEAST VERY DRUNK
		SHELF_PRICE - Was kind of a turd last X-MAS, so the gift is going to be CHEAP.
		
		SISTER
		ITEM_DESCRIPTION: LIKES CINNAMON OR PEPPERMINT FLAVORED DRINKS
		LIKES TO GET DRUNK
		VENDOR_NAME - Ex-Boyfriend works for 'Diageo Americas' and does not wish him well*/
		

		
/* INSTRUCTOR GUIDED - CASE STATEMENTS */

/*1. What is teh total count of products you could purchase for each family member? */

/*2. What is the MIN PRICE and MAX PRICE you'd have to pay for each family member? */

/* Can you represent the count of products for each family member as it's own indepdent column?*/


 /*CASE STATEMENT - INSTRUCTOR GUIDED*/

/* WITH THOSE PRODUCT LABELS, CAN WE FIND WHAT STORES CARRY THOSE PRODUCTS in IOWA? */

/* LOOK AT SALES TABLE */













